WHITESPACE = _{ " " }


identifier = { ASCII_DIGIT+ }

timecode = {(ASCII_DIGIT)+ ~ ":" ~ (ASCII_DIGIT){2} ~ ":" ~ (ASCII_DIGIT){2} ~ "," ~ (ASCII_DIGIT){3} }
startstop = { #start = timecode ~ "-->" ~ #stop = timecode }

header = { identifier ~ NEWLINE ~ startstop ~ NEWLINE }

line = { ( !header ~ ANY)* }

content = { line ~ (NEWLINE ~ line)* }


clip = {  header ~ content }

start = { NEWLINE* }

file = { SOI ~
    (clip)* ~ NEWLINE* ~
    EOI }
